// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Ozqxdq2uVlgK_aCy0Tsw-XZowGGjql0',
    appId: '1:212660161739:web:b7e9a3a61953b340569f4e',
    messagingSenderId: '212660161739',
    projectId: 'radar-chat-40f53',
    authDomain: 'radar-chat-40f53.firebaseapp.com',
    storageBucket: 'radar-chat-40f53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMYXzAHktHiAzwsWPEoDh1Sy483emq67Q',
    appId: '1:212660161739:android:55127f3a73589da6569f4e',
    messagingSenderId: '212660161739',
    projectId: 'radar-chat-40f53',
    storageBucket: 'radar-chat-40f53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnN8Oa1CarLtQkczzE6d_PTLiy52rUDag',
    appId: '1:212660161739:ios:0e2906c8e7be3687569f4e',
    messagingSenderId: '212660161739',
    projectId: 'radar-chat-40f53',
    storageBucket: 'radar-chat-40f53.appspot.com',
    iosBundleId: 'com.example.radar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnN8Oa1CarLtQkczzE6d_PTLiy52rUDag',
    appId: '1:212660161739:ios:0e2906c8e7be3687569f4e',
    messagingSenderId: '212660161739',
    projectId: 'radar-chat-40f53',
    storageBucket: 'radar-chat-40f53.appspot.com',
    iosBundleId: 'com.example.radar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Ozqxdq2uVlgK_aCy0Tsw-XZowGGjql0',
    appId: '1:212660161739:web:b40384c54ca22c38569f4e',
    messagingSenderId: '212660161739',
    projectId: 'radar-chat-40f53',
    authDomain: 'radar-chat-40f53.firebaseapp.com',
    storageBucket: 'radar-chat-40f53.appspot.com',
  );
}
